// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: polls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPoll = `-- name: CreatePoll :one
INSERT INTO polls(
    description,
    created_by
)
VALUES (
    $1,
    $2
) RETURNING id, description, created_by, is_active, created_at
`

type CreatePollParams struct {
	Description string      `json:"description"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

type CreatePollRow struct {
	ID          pgtype.UUID        `json:"id"`
	Description string             `json:"description"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (CreatePollRow, error) {
	row := q.db.QueryRow(ctx, createPoll, arg.Description, arg.CreatedBy)
	var i CreatePollRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deletePoll = `-- name: DeletePoll :one
DELETE FROM polls
WHERE id = $1
RETURNING  id, description, is_active, created_by, created_at, updated_at
`

func (q *Queries) DeletePoll(ctx context.Context, id pgtype.UUID) (Poll, error) {
	row := q.db.QueryRow(ctx, deletePoll, id)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPoll = `-- name: GetPoll :one
SELECT p.id, description, is_active, created_by, p.created_at, updated_at, po.id, poll_id, option_text, po.created_at FROM polls as p
JOIN public.poll_options po on p.id = po.poll_id
WHERE p.id=$1
`

type GetPollRow struct {
	ID          pgtype.UUID        `json:"id"`
	Description string             `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID_2        pgtype.UUID        `json:"id_2"`
	PollID      pgtype.UUID        `json:"poll_id"`
	OptionText  string             `json:"option_text"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetPoll(ctx context.Context, id pgtype.UUID) (GetPollRow, error) {
	row := q.db.QueryRow(ctx, getPoll, id)
	var i GetPollRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.PollID,
		&i.OptionText,
		&i.CreatedAt_2,
	)
	return i, err
}

const getPolls = `-- name: GetPolls :many
SELECT id, description, is_active, created_by, created_at, updated_at FROM polls
`

func (q *Queries) GetPolls(ctx context.Context) ([]Poll, error) {
	rows, err := q.db.Query(ctx, getPolls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Poll{}
	for rows.Next() {
		var i Poll
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePoll = `-- name: UpdatePoll :one
UPDATE polls
SET description=$2, is_active=$3
WHERE id = $1
RETURNING  id, description, is_active, created_by, created_at, updated_at
`

type UpdatePollParams struct {
	ID          pgtype.UUID `json:"id"`
	Description string      `json:"description"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) UpdatePoll(ctx context.Context, arg UpdatePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, updatePoll, arg.ID, arg.Description, arg.IsActive)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePollStatus = `-- name: UpdatePollStatus :one
UPDATE polls
SET is_active=$2
WHERE id = $1
RETURNING id, description, is_active, created_by, created_at, updated_at
`

type UpdatePollStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdatePollStatus(ctx context.Context, arg UpdatePollStatusParams) (Poll, error) {
	row := q.db.QueryRow(ctx, updatePollStatus, arg.ID, arg.IsActive)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
