// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: polls.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPoll = `-- name: CreatePoll :one
INSERT INTO polls(
    question,
    created_by
)
VALUES (
    $1,
    $2
) RETURNING id, question, created_by, is_active, created_at
`

type CreatePollParams struct {
	Question  string      `json:"question"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

type CreatePollRow struct {
	ID        uuid.UUID          `json:"id"`
	Question  string             `json:"question"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (CreatePollRow, error) {
	row := q.db.QueryRow(ctx, createPoll, arg.Question, arg.CreatedBy)
	var i CreatePollRow
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const disablePoll = `-- name: DisablePoll :one
UPDATE polls
SET is_active=$2
WHERE id = $1
RETURNING id, question, created_by, is_active, created_at, updated_at
`

type DisablePollParams struct {
	ID       uuid.UUID   `json:"id"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) DisablePoll(ctx context.Context, arg DisablePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, disablePoll, arg.ID, arg.IsActive)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
