// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePoll(ctx context.Context, arg CreatePollParams) (CreatePollRow, error)
	CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (PollOption, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error)
	DeletePoll(ctx context.Context, id pgtype.UUID) (Poll, error)
	DeletePollOption(ctx context.Context, id pgtype.UUID) (PollOption, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) (DeleteUserRow, error)
	DeleteVote(ctx context.Context, id pgtype.UUID) (Vote, error)
	GetOption(ctx context.Context, id pgtype.UUID) (PollOption, error)
	GetPoll(ctx context.Context, id pgtype.UUID) (GetPollRow, error)
	GetPolls(ctx context.Context) ([]Poll, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserDetails(ctx context.Context, id pgtype.UUID) (User, error)
	GetVote(ctx context.Context, id pgtype.UUID) (Vote, error)
	UpdatePoll(ctx context.Context, arg UpdatePollParams) (Poll, error)
	UpdatePollOption(ctx context.Context, arg UpdatePollOptionParams) (PollOption, error)
	UpdatePollStatus(ctx context.Context, arg UpdatePollStatusParams) (Poll, error)
	UpdateVoteOption(ctx context.Context, arg UpdateVoteOptionParams) (Vote, error)
}

var _ Querier = (*Queries)(nil)
