apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pollz-pvc
  namespace: pollz
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
