// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: polls.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPoll = `-- name: CreatePoll :one
INSERT INTO polls(
    description,
    created_by,
    active_until
)
VALUES (
    $1,
    $2,
    $3
) RETURNING id, description, active_until, created_by, created_at, updated_at
`

type CreatePollParams struct {
	Description string    `json:"description"`
	CreatedBy   uuid.UUID `json:"created_by"`
	ActiveUntil time.Time `json:"active_until"`
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, createPoll, arg.Description, arg.CreatedBy, arg.ActiveUntil)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.ActiveUntil,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePoll = `-- name: DeletePoll :one
DELETE FROM polls
WHERE id = $1
RETURNING  id, description, active_until, created_by, created_at, updated_at
`

func (q *Queries) DeletePoll(ctx context.Context, id uuid.UUID) (Poll, error) {
	row := q.db.QueryRow(ctx, deletePoll, id)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.ActiveUntil,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPoll = `-- name: GetPoll :one
SELECT id, description, active_until, created_by, created_at, updated_at FROM polls
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPoll(ctx context.Context, id uuid.UUID) (Poll, error) {
	row := q.db.QueryRow(ctx, getPoll, id)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.ActiveUntil,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPollWithOptions = `-- name: GetPollWithOptions :one
SELECT p.id, description, active_until, created_by, p.created_at, updated_at, po.id, poll_id, option_text, po.created_at FROM polls as p
JOIN poll_options as po ON p.id = po.poll_id
WHERE p.id = $1
`

type GetPollWithOptionsRow struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
	ActiveUntil time.Time `json:"active_until"`
	CreatedBy   uuid.UUID `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID_2        uuid.UUID `json:"id_2"`
	PollID      uuid.UUID `json:"poll_id"`
	OptionText  string    `json:"option_text"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) GetPollWithOptions(ctx context.Context, id uuid.UUID) (GetPollWithOptionsRow, error) {
	row := q.db.QueryRow(ctx, getPollWithOptions, id)
	var i GetPollWithOptionsRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.ActiveUntil,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.PollID,
		&i.OptionText,
		&i.CreatedAt_2,
	)
	return i, err
}

const getPolls = `-- name: GetPolls :many
SELECT id, description, active_until, created_by, created_at, updated_at FROM polls
`

func (q *Queries) GetPolls(ctx context.Context) ([]Poll, error) {
	rows, err := q.db.Query(ctx, getPolls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Poll{}
	for rows.Next() {
		var i Poll
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.ActiveUntil,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePoll = `-- name: UpdatePoll :one
UPDATE polls
SET description=$2, active_until=$3
WHERE id = $1
RETURNING  id, description, active_until, created_by, created_at, updated_at
`

type UpdatePollParams struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
	ActiveUntil time.Time `json:"active_until"`
}

func (q *Queries) UpdatePoll(ctx context.Context, arg UpdatePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, updatePoll, arg.ID, arg.Description, arg.ActiveUntil)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.ActiveUntil,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePollStatus = `-- name: UpdatePollStatus :one
UPDATE polls
SET active_until=$2
WHERE id = $1
RETURNING id, description, active_until, created_by, created_at, updated_at
`

type UpdatePollStatusParams struct {
	ID          uuid.UUID `json:"id"`
	ActiveUntil time.Time `json:"active_until"`
}

func (q *Queries) UpdatePollStatus(ctx context.Context, arg UpdatePollStatusParams) (Poll, error) {
	row := q.db.QueryRow(ctx, updatePollStatus, arg.ID, arg.ActiveUntil)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.ActiveUntil,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
